---
title: nftyventures
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  team:
    title: Team
    output: true
  uploads:
    title: Uploads
    output: true
email: info@nftyventures.io
description: homepage of nfty ventures
baseurl: ''
url: ''
plugins:
- jekyll-feed
sass:
  sass_dir: _sass
  style: compressed
exclude:
- ".sass-cache/"
- ".jekyll-cache/"
- gemfiles/
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
